### ISSUE TITLE
Section "Contactez Nous" : Ajouter numéro téléphone, courriel et adresse

### ISSUE THREAD

**Issue by dominic195** [dominic195/CFL-Website#10]
Dom : (514) 775-3901 Julie : (514) 889-2024
email : info@clubfleuretdelys.com
adresse : École primaire St-Lucien
121 Lafontaine, Saint-Jean-sur-Richelieu, QC J3B 5E4
Entrée sur la rue des Trinitaires à partir de la cour de récréation.

**Comment by jiojojo** [comment]
Je l'ai mis sous "Contactez nous" je ne trouvais pas ça pertinent de faire une page pour juste ça.

**Comment by dominic195** [comment]
Oui, je parlais de cette section, faudrait juste ajouter ces coordonnées dans la page
