### ISSUE TITLE
Ajouter le timeline de la page facebook

### ISSUE THREAD

**Issue by Dom-Rousseau** [dominic195/CFL-Website#13]
Soit sur la page d'acceuil, ou dans la section Nouvelles.

link pour générer le code: [https://developers.facebook.com/docs/plugins/page-plugin](https://developers.facebook.com/docs/plugins/page-plugin)

voici un exemple du code avec un Iframe:
`<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffleuretdelys&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>`

**Comment by jiojojo** [comment]
De ce que je comprend Dom va devoir mettre de quoi sur la page du club pour fitter avec le code.

**Comment by jiojojo** [comment]
@donmici Tu checkeras le lien que Dom a mis.

**Comment by Dom-Rousseau** [comment]
finalement j'ai ajouté le widget du sidebar Facebook page, ca faisait exactement le même code que mon exemple en haut.

trouvez-vous ca trop de l'avoir dans le sidebar tout le temps ?

**Comment by jiojojo** [comment]
Je propose de retirer le bouton qui mène à la page facebook, il perd de son utilité, et de déplacer la dernière nouvelle dans un footer tierce. Ça devrait libérer assez d'espace pour avoir l'air plus propre.

Je vais le faire immédiatement puisque ça ne prend que quelques minutes à modifier il sera facile de revenir à la dernière itération selon la préférence.

**Comment by jiojojo** [comment]
Si vous trouvez ça correct de la manière que j'ai fait, je vais close cet issue.

**Comment by dominic195** [comment]
Yep, je pense pas qu'on va avoir beaucoup mieux
